dist: trusty
sudo: required
language: node_js
node_js:
  - node

cache:
  yarn: true

before_script:
  - yarn global add cordova ionic
  - mkdir www

script:
  - yarn lint
  - yarn lint:css
  - cordova prepare
  - yarn build
