# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          # Cache gradle directories
          path: |
            ~/.gradle/caches
            ~/.gradle/native
            ~/.gradle/wrapper
          # Key for restoring and saving the cache
          key: ${{ runner.os }}-gradle

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '13'

      - name: Copy aRMT secrets
        run: 'echo "$SECRET" > src/assets/data/secret.ts'
        shell: bash
        env:
          SECRET: ${{secrets.SECRET_TS}}

      - name: Install Cordova
        run: npm i -g cordova

      - name: Install Ionic
        run: npm i -g ionic

      - name: Install app dependencies
        run: yarn install

      - name: Add Android platform
        run: ionic cordova platform add android && rm package-lock.json

      - name: Build Android app
        run: |
          cordova prepare android && \
          yarn install && yarn add rxjs && \
          ionic cordova build android
