# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  release:
    types: [published]

env:
  PACKAGE_NAME_ANDROID: org.phidatalab.radar_armt
  KEYSTORE_PATH: radar-armt-release-key.keystore
  KEYSTORE_ALIAS: alias_name
  PLAYSTORE_SERVICE_KEY: service-api.json
  PLAYSTORE_TRACK: alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          # Cache gradle directories
          path: |
            ~/.gradle/caches
            ~/.gradle/native
            ~/.gradle/wrapper
          # Key for restoring and saving the cache
          key: ${{ runner.os }}-gradle

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '13'

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Copy aRMT secrets
        run: 'echo "$SECRET" > src/assets/data/secret.ts'
        shell: bash
        env:
          SECRET: ${{secrets.SECRET_TS}}

      - name: Install Cordova
        run: npm i -g cordova

      - name: Install Ionic
        run: npm i -g ionic

      - name: Install app dependencies
        run: yarn install

      - name: Add Android platform
        run: ionic cordova platform add android && rm package-lock.json

      - name: Run unit tests
        run: xvfb-run -a yarn test

      - name: Build Android app
        run: |
          cordova prepare android && \
          yarn install && yarn add rxjs

      - name: Deploy Android app to Play Store
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android deploy'
          options: '{ "keystore_path": $KEYSTORE_PATH, "keystore_password": ${{secrets.KEYSTORE_PASS}}, "keystore_alias": $KEYSTORE_ALIAS, "package_name": $PACKAGE_NAME_ANDROID, "track": $PLAYSTORE_TRACK, "json_key": $PLAYSTORE_SERVICE_KEY }'
